name: CD for Prod

on:
    workflow_dispatch:
        inputs:
            test:
                description: 'ğŸ”¦ QA lead already approved'
                required: true
                type: boolean
            sign-off:
                description: 'ğŸ“ Make sure PO sign-off'
                required: true
                type: boolean
            deploy-tag:
                description: 'ğŸ¯ Deploy docker tag'
                required: true
                type: string
                default: c9f6b38c1acd0a7153e42a03b577757262075eb3

jobs:
    gitops-prd-versioning:
        runs-on: ubuntu-latest
        steps:
            -   name: verify manual input
                run: |
                    { if [ '${{ inputs.test }}' = 'false' ]; then echo "ğŸ”¦ QA lead not approve yet"; exit 1; fi }
                    { if [ '${{ inputs.sign-off }}' = 'false' ]; then echo "ğŸ“ Need PO sign-off"; exit 1; fi }

            -   name: checkout
                uses: actions/checkout@v3

            -   name: config git
                run: |
                    git --version
                    git config user.name "robot"
                    git config user.email "root@werockstar.dev"

            -   name: change image tag
                run: |
                    sed -i -E "s/werockstar\/workshop-summer.*$/werockstar:${GITHUB_SHA}/" infra/gitops/prod/deployment.yml
                    git add infra/gitops/prod/deployment.yml
                    git commit -m "[skip actions] ğŸ¤– change prd docker image version to ${{ inputs.deploy-tag }}"
                    git pull --rebase
                    git push
